### DISCUSSION TITLE
For self hosted instances: enable magic links to polls and password protect main page.

### DISCUSSION THREAD

**Discussion by aikiharp** [lukevella/rallly#126] [Ideas]
I want to host an instance of Rallly on my home server, but I don't want to have it accessible to the world unless I'm sending out a poll for responses.  Therefore, I'd like to password protect the app, but allow respondents to be able to use a magic link that gives them access to the specific poll without needing to login.  I can protect the whole app via NGINX reverse proxy authentication, but that means respondents will need to use the same login/password.

**Comment by lukevella** [comment]
Hi thanks for bringing up this use case. I'll consider adding some configuration in the future so only authenticated users can create polls but to be completely honest it's fairly low on the priority list so maybe you can using something like [authelia](https://github.com/authelia/authelia) to do this in the meantime.

**Reply by mattprecious** [reply]
I think I've managed to make it work, but it's not very practical since there's no simple way to separate protected "admin" traffic from allowed public traffic. Also since there's far fewer protected resources, I've chosen to use a deny list instead of an allow list, which means that the failure mode if the APIs change is that protected resources get exposed, which is not great.

Here's the configuration I've currently landed on:

```yaml
access_control:
  default_policy: deny

  rules:
    - domain:
      - rallly.mydomain.com
      policy: two_factor
      resources:
        - '^/$'
        - '^/demo'
        - '^/new'
        - '^/admin'
        - '^/api/trpc/polls.create'
        - '^/api/trpc/polls.update'
        - '^/api/trpc/polls.delete'

    - domain:
      - rallly.mydomain.com
      policy: bypass
```

Have I missed any resources?
