### DISCUSSION TITLE
Creating polls (demo poll) doesnt work with Docker

### DISCUSSION THREAD

**Discussion by blazekjan** [lukevella/rallly#186] [Q&A]
Hello,
I have a trouble running Rallly in Docker. I tried to spin up the containers on two different machines, however I am still being stuck. What did I do:

1) edited docker-compose to have db-data in docker-compose DIR (as everything gets pulled and it is automatically backed up)
   - ./db-data:/var/lib/postgresql/data
2) edited .env, and commented out (as stated in readme)
   DATABASE_URL=postgres://your-database/db 
   set up 32 characters long SECRET_PASSWORD
   set up SMTP, where I used same credentials as for vaultwarden which works
3) hit docker compose up -d

What do I get:

```
[+] Running 3/0
 ⠿ Network rallly_default        Created                                                                                                                                                                                                                                                                                                                            0.0s
 ⠿ Container rallly-rallly_db-1  Created                                                                                                                                                                                                                                                                                                                            0.0s
 ⠿ Container rallly-rallly-1     Created                                                                                                                                                                                                                                                                                                                            0.0s
Attaching to rallly-rallly-1, rallly-rallly_db-1
rallly-rallly_db-1  |
rallly-rallly_db-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
rallly-rallly_db-1  |
rallly-rallly_db-1  | 2022-05-23 21:50:58.112 UTC [1] LOG:  starting PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
rallly-rallly_db-1  | 2022-05-23 21:50:58.112 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
rallly-rallly_db-1  | 2022-05-23 21:50:58.112 UTC [1] LOG:  listening on IPv6 address "::", port 5432
rallly-rallly_db-1  | 2022-05-23 21:50:58.112 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
rallly-rallly_db-1  | 2022-05-23 21:50:58.114 UTC [25] LOG:  database system was shut down at 2022-05-23 21:50:50 UTC
rallly-rallly_db-1  | 2022-05-23 21:50:58.120 UTC [1] LOG:  database system is ready to accept connections
rallly-rallly-1     | yarn run v1.22.19
rallly-rallly-1     | $ /usr/src/app/node_modules/.bin/prisma migrate deploy --schema prisma/schema.prisma
rallly-rallly-1     | Prisma schema loaded from prisma/schema.prisma
rallly-rallly-1     | Datasource "db": PostgreSQL database "db", schema "public" at "rallly_db:5432"
rallly-rallly-1     |
rallly-rallly-1     | 17 migrations found in prisma/migrations
rallly-rallly-1     |
rallly-rallly-1     |
rallly-rallly-1     | No pending migrations to apply.
rallly-rallly_db-1  | 2022-05-23 21:51:00.681 UTC [33] LOG:  could not receive data from client: Connection reset by peer
rallly-rallly-1     | Done in 2.25s.
rallly-rallly-1     | yarn run v1.22.19
rallly-rallly-1     | $ next start
rallly-rallly-1     | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
```
docker-compose.yml

```
version: "3.3"
services:
  rallly_db:
    image: postgres:14.2
    restart: always
    volumes:
      - ./db-data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  rallly:
    build:
      context: .
      args:
        - DATABASE_URL=postgres://postgres:postgres@rallly_db:5432/db?pgbouncer=true
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    restart: always
    command: sh -c "yarn prisma migrate deploy --schema prisma/schema.prisma && yarn start"
    depends_on:
      - rallly_db
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@rallly_db:5432/db
    env_file:
      - .env

volumes:
  db-data:
    driver: local
```
.env

```
NEXT_PUBLIC_BASE_URL=http://localhost:3000
#DATABASE_URL=postgres://your-database/db
SECRET_PASSWORD=*redacted*
SUPPORT_EMAIL=*redacted*
SMTP_HOST=smtp.sendgrid.net
SMTP_PORT=465
SMTP_SECURE=true
SMTP_USER=apikey
SMTP_PWD=*redacted*
```

I can't create any polls and demo poll doesnt work either. Its stuck on Creating demo poll and I get: Uh oh! Something went wrong. The issue has been logged and we'll fix it as soon as possible. Please try again later.

Just checked recently closed issues and found #178 Any chance it has something to do with?
