### DISCUSSION TITLE
Only allow admins to create polls

### DISCUSSION THREAD

**Discussion by brettinternet** [lukevella/rallly#352] [Ideas]
This feature request is to only allow admins to create new polls.

Related: #152

**Comment by brettinternet** [comment]
# Workaround

It's difficult to prevent access to certain paths because the frontend is a SPA and routing is done on the client. However, we can put certain API paths behind authentication via a reverse proxy. This could, however, be a workaround if we could have a list of API paths that should be allowed for all responding users.

Here's an example definition for an Ingress definition.

Poll responders:

```yml
- path: /p/
  pathType: Prefix
- path: /_next/
  pathType: Prefix
- path: /site.webmanifest
  pathType: Exact
- path: /api/trpc/polls.touch
  pathType: Prefix
- path: /api/trpc/session.get
  pathType: Prefix
- path: /api/trpc/polls.get
  pathType: Prefix
- path: /api/trpc/polls.comments.list
  pathType: Prefix
- path: /api/trpc/polls.commands.add
  pathType: Prefix
- path: /api/trpc/polls.participants.list
  pathType: Prefix
- path: /api/trpc/polls.participants.add
  pathType: Prefix
```

I'm sure there are others, too.

For the API calls, those should probably use regex instead since it looks like some API calls are chained so that a prefix wouldn't work. (e.g. `/api/trpc/polls.get,session.get?...`)

Admins only catch-all:

```yml
- path: /
  pathType: Prefix
```

Am I missing any?
