### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by EbbeVang** [lukevella/rallly#1004]
I have installed a postgres server and the db is successfully migtrated. But when I visit the site i am taken to /poll and get an internal server error:

a piece of the containers log:

```
rallly  | No pending migrations to apply.
1893   │ rallly  |    ▲ Next.js 14.0.1
1894   │ rallly  |    - Local:        http://8b17ba1899ad:3000
1895   │ rallly  |    - Network:      http://172.23.0.6:3000
1896   │ rallly  | 
1897   │ rallly  |  ✓ Ready in 312ms
1898   │ rallly  | TypeError [ERR_INVALID_URL]: Invalid URL
1899   │ rallly  |     at new NodeError (node:internal/errors:405:5)
1900   │ rallly  |     at new URL (node:internal/url:676:13)
1901   │ rallly  |     at parseUrl (/app/apps/web/.next/server/src/middleware.js:11311:18)
1902   │ rallly  |     at handleMiddleware (/app/apps/web/.next/server/src/middleware.js:11240:44)
1903   │ rallly  |     at Object.options (/app/apps/web/.next/server/src/middleware.js:11280:39)
1904   │ rallly  |     at Object.<anonymous> (/app/apps/web/.next/server/src/middleware.js:6856:49)
1905   │ rallly  |     at Object.apply (/app/apps/web/.next/server/src/middleware.js:567:16)
1906   │ rallly  |     at /app/apps/web/.next/server/src/middleware.js:13064:23
1907   │ rallly  |     at AsyncLocalStorage.run (node:async_hooks:338:14)
1908   │ rallly  |     at Object.wrap (/app/apps/web/.next/server/src/middleware.js:12865:24) {
1909   │ rallly  |   input: '',
1910   │ rallly  |   code: 'ERR_INVALID_URL'
1911   │ rallly  | }
```

any suggestions are appreciated - I don't know what to do now :-) 

I use this docker compose file: (changed postgres login snd renamed domain name but everything else is like this:

```
rallly:
    image: lukevella/rallly:3
    restart: always
    container_name: rallly
    depends_on:
       - postgres
     expose:
        - 3000
     environment:
        - DATABASE_URL=postgres://rallly_user:top_secret_pass@postgres:5432/rallly
        - NEXT_PUBLIC_BASE_URL=https://rallly.evang.dk
        - SECRET_PASSWORD=bbUV4bPdbDAZV9IDBIu4WPE807pmRa7tyJMGmUlTxh0=
        - SUPPORT_EMAIL=initials@mydomain.com
        - ALLOWED_EMAILS=initials@mydomain.com
        - NOREPLY_EMAIL=rallly@mydomain.com
        - SMTP_HOST=smtp.gmail.com
        - SMTP_PORT=587
       - SMTP_USER=me@example.com
       - SMTP_PWD=xxxxxxxxxxxxxxx
       - SMTP_TLS_ENABLED=true

```
