### ISSUE TITLE
Don´t run in Docker Compose on Raspberry Pi 5

### ISSUE THREAD

**Issue by vic-951** [lukevella/rallly#1051]
**Describe the bug**
Hello there, I tried to run rallly with the docker compose file from lukevella. But it won´t start.

**To Reproduce**
start docker with this yaml and .env file:
```
version: "3"
services:
  rallly_db:
    image: postgres:latest
    container_name: rallly-db
    restart: always
    volumes:
      - /home/user/docker/rallly/db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rallly:
    image: lukevella/rallly:latest
    container_name: rallly-app
    restart: always
    depends_on:
      - rallly_db
    ports:
      - 7006:3000
    env_file:
      - .env
networks:
  rallly:
    external: true
```

```
# REQUIRED CONFIG

# A postgres database connection string.
# Does not need to be defined if you are using the docker-compose file in this repository
# to run your database.
DATABASE_URL=postgres://postgres:passwd@rallly_db:5432/db

# A random 32-character secret key used to encrypt user sessions
SECRET_PASSWORD=key

# The base url where this instance is accessible, including the scheme.
# Example: https://example.com
NEXT_PUBLIC_BASE_URL=https://url

# Comma separated list of email addresses that are allowed to register and login.
# You can use wildcard syntax to match a range of email addresses.
# Example: "john@example.com,jane@example.com" or "*@example.com"
ALLOWED_EMAILS=

# EMAIL CONFIG (required for sending emails)

# The email address that will be used to send emails. If not set, SUPPORT_EMAIL will be used instead.
NOREPLY_EMAIL=

# The email of whoever is managing this instance in case a user needs support.
SUPPORT_EMAIL=mail@dom.de

# The host address of your SMTP server
SMTP_HOST=smtp.server.de

# The port of your SMTP server
SMTP_PORT=465

# Set to "true" if SSL is enabled for your SMTP connection
SMTP_SECURE=true

# The username (if auth is enabled on your SMTP server)
SMTP_USER=mail@dom.de

# The password (if auth is enabled on your SMTP server)
SMTP_PWD=passwd

# Postgres
POSTGRES_PASSWORD=passwd
POSTGRES_DB=db
```

**Expected behavior**
starting of docker container

**Output Docker**
rallly-1     | exec /usr/local/bin/docker-entrypoint.sh: exec format error
rallly-1 exited with code 0
