### ISSUE TITLE
[BUG] Internal Server Error: Invalid URL

### ISSUE THREAD

**Issue by dodekaphilist** [lukevella/rallly#1073]
**Describe the bug**
Similar to #1004, creation and migration of the database is successful. When visiting the site, after a forward to `/polls` I get an internal server error with the logs listing `ERR_INVALID_URL` on each page reload. I tried both accessing via IP/port and domain names using a reverse proxy with no difference.

**compose.yaml**
```
version: "3"
services:
  rallly_db:
    image: postgres:14.2
    container_name: rallly_db
    restart: always
    volumes:
      - /volume1/docker/rallly/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
  rallly:
    image: lukevella/rallly:3.7.0
    container_name: rallly_server
    restart: always
    depends_on:
      - rallly_db
    ports:
      - 3079:3000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@rallly_db:5432/db
```
**.env**
```
SECRET_PASSWORD=pwd
NEXT_PUBLIC_BASE_URL=https://sub.domain.tld
ALLOWED_EMAILS=*
SUPPORT_EMAIL=support@sub.domain.tld
SMTP_HOST=smtp.ionos.de
SMTP_PORT=465
SMTP_SECURE=true
SMTP_USER=mail@domain.tdl
SMTP_PWD=pwd
```

**Logs**
```
rallly_db      | PostgreSQL Database directory appears to contain a database; Skipping initialization
rallly_db      | 
rallly_db      | 2024-04-02 15:42:15.757 UTC [1] LOG:  starting PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
rallly_db      | 2024-04-02 15:42:15.780 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
rallly_db      | 2024-04-02 15:42:15.780 UTC [1] LOG:  listening on IPv6 address "::", port 5432
rallly_db      | 2024-04-02 15:42:16.421 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
rallly_db      | 2024-04-02 15:42:17.623 UTC [33] LOG:  database system was shut down at 2024-04-02 15:37:02 UTC
rallly_db      | 2024-04-02 15:42:17.623 UTC [34] FATAL:  the database system is starting up
rallly_db      | 2024-04-02 15:42:17.708 UTC [1] LOG:  database system is ready to accept connections
rallly_server  | Prisma schema loaded from prisma/schema.prisma
rallly_server  | Datasource "db": PostgreSQL database "db", schema "public" at "rallly_db:5432"
rallly_server  | 
rallly_server  | 50 migrations found in prisma/migrations
rallly_server  | 
rallly_server  | No pending migrations to apply.
rallly_db      | 2024-04-02 15:42:21.527 UTC [42] LOG:  could not receive data from client: Connection reset by peer
rallly_server  |    ▲ Next.js 14.0.4
rallly_server  |    - Local:        http://localhost:3000
rallly_server  |    - Network:      http://0.0.0.0:3000
rallly_server  |  ✓ Ready in 1348ms
rallly_server  | TypeError [ERR_INVALID_URL]: Invalid URL
rallly_server  |     at new NodeError (node:internal/errors:405:5)
rallly_server  |     at new URL (node:internal/url:676:13)
rallly_server  |     at parseUrl (/app/apps/web/.next/server/src/middleware.js:814:18)
rallly_server  |     at handleMiddleware (/app/apps/web/.next/server/src/middleware.js:743:44)
rallly_server  |     at Object.options [as handler] (/app/apps/web/.next/server/src/middleware.js:783:39)
rallly_server  |     at /app/apps/web/.next/server/src/middleware.js:4445:27
rallly_server  |     at AsyncLocalStorage.run (node:async_hooks:338:14)
rallly_server  |     at Object.wrap (/app/apps/web/.next/server/src/middleware.js:3954:24)
rallly_server  |     at /app/apps/web/.next/server/src/middleware.js:4432:47
rallly_server  |     at NoopContextManager.with (/app/apps/web/.next/server/src/middleware.js:1559:30) {
rallly_server  |   input: '',
rallly_server  |   code: 'ERR_INVALID_URL'
rallly_server  | }
rallly_server  |  ⨯ TypeError [ERR_INVALID_URL]: Invalid URL
rallly_server  |     at new NodeError (node:internal/errors:405:5)
rallly_server  |     at new URL (node:internal/url:676:13)
rallly_server  |     at parseUrl (/app/node_modules/next-auth/utils/parse-url.js:17:16)
rallly_server  |     at Object.<anonymous> (/app/node_modules/next-auth/react/index.js:72:34)
rallly_server  |     at Module._compile (node:internal/modules/cjs/loader:1356:14)
rallly_server  |     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
rallly_server  |     at Module.load (node:internal/modules/cjs/loader:1197:32)
rallly_server  |     at Module._load (node:internal/modules/cjs/loader:1013:12)
rallly_server  |     at Module.require (node:internal/modules/cjs/loader:1225:19)
rallly_server  |     at mod.require (/app/node_modules/next/dist/server/require-hook.js:65:28) {
rallly_server  |   input: '',
rallly_server  |   code: 'ERR_INVALID_URL'
rallly_server  | }
```

Please let me know, if I need to provide more information.
