### ISSUE TITLE
FATAL:  role "postgres" does not exist

### ISSUE THREAD

**Issue by gremo** [lukevella/rallly#1492]
Rallly works without any issue, but logs are flooded with the following error:

> FATAL:  role "postgres" does not exist

I've created the Compose project this way (this is just a part of the configuration):

```yaml
services:
    rallly:
        image: lukevella/rallly:latest
        environment:
            DATABASE_URL: postgres://rallly:${DB_PASSWORD:?}@db.local/rallly

    db:
        image: postgres:14
        environment:
            POSTGRES_USER: rallly
            POSTGRES_PASSWORD: ${DB_PASSWORD:?}
            POSTGRES_DB: rallly
```

Does the error occur because I didn't used the default psotgres superuser?
