### ISSUE TITLE
Recent update broke docker deploy

### ISSUE THREAD

**Issue by jurij-robba** [lukevella/rallly#1740]
**Describe the bug**
after updating to latest image, the docker container keeps restarting. It worked perfectly before. docker logs show:

Error: Can't write to /pnpm/global/5/.pnpm/@prisma+engines@6.8.2/node_modules/@prisma/engines please make sure you install "prisma" with the right permissions.

**To Reproduce**

create docker file like this:

```
services:
  rallly:
    image: lukevella/rallly:latest
    container_name: rallly
    restart: always
    hostname: 0.0.0.0
    user: ${PID}:${PID}
    depends_on:
      - rallly_db
    environment:
      - DATABASE_URL=postgres://postgres:${RALLY_DB_PASSWORD}@rallly_db:5432/rallly
      - SECRET_PASSWORD=${RALLLY_PASSWORD}
      - NEXT_PUBLIC_BASE_URL=https://time.robba.art
      - ALLOWED_EMAILS=<redacted>
      - NOREPLY_EMAIL=<redacted>
      - SUPPORT_EMAIL=<redacted>
      - SMTP_TLS_ENABLED=true
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=<redacted>
      - SMTP_PWD=${SMTP_PASSWORD}
    ports:
      - 4000:3000
    networks:
      - rallly

  rallly_db:
    image: postgres:14.2
    container_name: rallly_db
    restart: always
    volumes:
      - ~/Docker/rallly_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${RALLY_DB_PASSWORD}
      - POSTGRES_DB=rallly
    networks:
      - rallly
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries:  5
```

run `docker compose up`

**Expected behavior**

docker compose up should bring the working container up. instead container is restarting

**Desktop (please complete the following information):**

- OS: docker on debian
- Browser not relevant
- Version :latest

**Additional context**
This setup worked nicely until update yesterday.
