### ISSUE TITLE
Docker build takes a very long time

### ISSUE THREAD

**Issue by lukevella** [lukevella/rallly#391]
After adding support for building a multi-platform image (#175) the workflow for [building and pushing images to docker hub](https://github.com/lukevella/rallly/actions/workflows/docker-image.yml) went from taking under 5 minutes to over an hour.

The issue seems to be that building the project takes almost an hour for arm64 whereas it takes only about a minute for amd64.

**Comment by gdnmhr** [comment]
AFAIK this is currently inevitable, as GitHub Actions currently only have `x86` runners. Thus, building `arm64` images needs to be virtualized (in this case `buildx` uses `QEMU`) which is obviously much slower than building natively.

It seems like [`arm64` runners are on the roadmap](https://github.com/actions/runner-images/issues/5631),  but unfortunately it doesn't seem likely they appear soon. The only option apart from `QEMU` would be to use a self-hosted runner, but that seems like too much effort for this.

For increased productivity you could consider adding another workflow which only builds the `x86` image so you get the results faster and can test changes while the `arm64` image finishes to build.

**Comment by Just5KY** [comment]
You can try adding build cache

```yml

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: justsky.dockerfile
          platforms: linux/arm64, linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/rally:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/rally:buildcache,mode=max
```
